# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSISDNInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.BigIntegerField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIMCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICCID', models.BigIntegerField(max_length=20, unique=True)),
                ('IMSI', models.BigIntegerField(max_length=15)),
                ('Ki', models.CharField(max_length=20)),
                ('PIN1', models.IntegerField(max_length=4)),
                ('PUC', models.IntegerField(max_length=6)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SIMSwapHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.BigIntegerField(max_length=12)),
                ('ICCID', models.BigIntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.BigIntegerField(max_length=12, unique=True)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.BigIntegerField(max_length=12, unique=True)),
                ('AccountBalance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='msisdninfo',
            name='ICCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SIMCard'),
        ),
    ]
