# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 08:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190613_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='ICCID',
            field=models.DecimalField(decimal_places=0, max_digits=20, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 20', regex='^.{20}$')]),
        ),
    ]
